M48
; DRILL file {KiCad (6.0.5)} date ven. 03 juin 2022 16:10:35
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-03T16:10:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X3.84Y-1.9
X3.84Y-1.95
X3.84Y-2.05
X4.0Y-1.85
X4.0Y-1.9
X4.425Y-1.8
T2
X4.25Y-1.9
X4.25Y-2.0
X4.25Y-2.1
X4.35Y-1.9
X4.35Y-2.0
X4.35Y-2.1
T3
X4.2Y-2.25
X4.3Y-1.75
X4.4Y-2.25
T0
M30
